import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hix/extensions/extension.dart';
import 'package:hix/models/model.dart';
import 'package:hix/shared/shared.dart';
import 'package:shimmer/shimmer.dart';

part 'floating_back_button.dart';
part 'browse_button.dart';
part 'cast_card.dart';
part 'coming_soon_card.dart';
part 'date_card.dart';
part 'empty_state.dart';
part 'gradient_fab.dart';
part 'movie_card.dart';
part 'promo_card.dart';
part 'rating_stars.dart';
part 'selectable_box.dart';
